Description: >
  Deploys an Application Load Balancer that exposes our ghost service on port 80.

Parameters:

  EnvironmentName: 
    Description: An environment name that will be prefixed to resource names.
    Type: String

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: choose which vpc the application load balancer should be deployed to

  Subnets:
    Description: reference to subnet1
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroup:
    Description: security group to apply to the alb
    Type: AWS::EC2::SecurityGroup::Id

  Path:
    Description: the path to register with the application load balancer
    Type: String

Resources:

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref EnvironmentName
      Subnets: !Ref Subnets
      SecurityGroups:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref Listener
      Priority: 1
      Conditions:
        - Field: path-pattern
          Values:
            - !Ref Path
      Actions:
        - TargetGroupArn: !Ref DefaultTargetGroup
          Type: forward

  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-default
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2

Outputs:

  LoadBalancer:
    Description: a reference to the application load balancer id
    Value: !Ref LoadBalancer

  LoadBalancerUrl:
    Description: the url of the application load balancer
    Value: !GetAtt LoadBalancer.DNSName

  LoadBalancerListener:
    Description: A reference to a port 80 listener
    Value: !Ref Listener

  LoadBalancerTargetGroup:
    Description: a reference to the defeault load balancer target group
    Value: !Ref DefaultTargetGroup


